name: pypi

on:
  push:
    branches:
    - main
    - dev
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+.test'
  pull_request:
    branches:
    - main
    - dev

jobs:
  build:
    name: Build and check distribution 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install build twine --user
    - name: Build a binary wheel and a source tarball and check them
      run: |
        python3 -m build .
        python3 -m twine check dist/*
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    if: github.repository == 'jixingcn/sphinxcontrib-twine' && github.ref_type == 'tag' && !endsWith(github.ref, '.test')
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/sphinxcontrib-twine

    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    if: github.repository == 'jixingcn/sphinxcontrib-twine' && github.ref_type == 'tag' && endsWith(github.ref, '.test')
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/sphinxcontrib-twine

    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  release-to-github:
    name: Release to github
    if: github.repository == 'jixingcn/sphinxcontrib-twine' && github.ref_type == 'tag' && !endsWith(github.ref, '.test')
    needs:
    - build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*.whl
          dist/*.gz
